<a href="https://colab.research.google.com/github/jajuangraham/deep-learning-challenge/blob/main/charity_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
# Load the dataset from the provided URL
url = "https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv"
application_df = pd.read_csv(url)

# Display the first few rows
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
application_df = application_df.drop(columns=["EIN", "NAME"])

In [6]:
# Define the target and feature columns
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns=["IS_SUCCESSFUL"])

In [7]:
# Number of unique values per column
unique_counts = X.nunique()
print(unique_counts)

# Show counts for columns with more than 10 unique values
for column in X.columns:
    if X[column].nunique() > 10:
        print(f"\nValue counts for {column}:\n", X[column].value_counts())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
dtype: int64

Value counts for APPLICATION_TYPE:
 APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

Value counts for CLASSIFICATION:
 CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1248        1
C6100        1
C1820        1
C1900        1
C2150        1
Name: count, Length: 71, dtype: int64

Value counts for ASK_AMT:
 ASK_AMT
5000        25398
6725            3
63981           3
15583           3
10478           3
            ...
343705          1
68431793        1
119369          1
1318537         1
37365916        1
Name: count, Length: 8747, dtype: int64

In [8]:
# Application Type cleanup
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
rare_apps = app_type_counts[app_type_counts < 500].index
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(rare_apps, "Other")

# Classification cleanup
class_counts = application_df['CLASSIFICATION'].value_counts()
rare_classes = class_counts[class_counts < 1000].index
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(rare_classes, "Other")

In [9]:
# Convert categorical variables to dummy/indicator variables
application_df = pd.get_dummies(application_df)

In [10]:
# Redefine X and y after encoding
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns=["IS_SUCCESSFUL"])

# Split into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit on training data, transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)